# Generated by Django 6.0.3 on 2026-03-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
