# Generated by Django 6.0.3 on 2026-03-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='telegram',
            field=models.CharField(default='', max_length=255),
        ),
    ]
